### ISSUE TITLE
Splitting up CTFs to make the repo more acccessbile

### ISSUE THREAD

**Issue by cm-recruit** [ctfs/write-ups-2016#1]
I think using a single branch per ctf might be a good way to go about it. For 2016, you can make an empty branch now then the process is:
1. *git clone -b empty_ctf --single-branch [url]* \(or *git checkout empty_ctf* if you are the maintainer of the master\)
2. *git checkout -b [ctf_name]*

or if the branch already exists for that ctf:
1. *git clone -b [ctf_name] --single-branch [url]*

Then once this branch exists the maintainer of the master just needs to:
1. *git checkout master*
2. *git merge [ctf_name]*

A single branch per ctf allows people to work on the repository without having to clone the entire master branch as it gets bigger. Github also allows users to download a zip of specific branches from the website which is very nice if people want to download a particular ctf and play with those challenges.

I was messing around with the idea here: https://github.com/cm-recruit/write-ups-2016/tree/master

**Comment by YASME-Tim** [comment]
As discussed in detail [here[(https://github.com/ctfs/write-ups-2015/issues/619) :)
