### ISSUE TITLE
Insomni'hack teaser 2016 Bring the noise team Against All Authority

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2016#14]
Insomni'hack teaser 2016 Bring the noise team Against All Authority<br>
https://ctftime.org/writeup/2286<br>
https://adriancohea.ninja/bring-the-noise-insomnihack-teaser-2016/<br><br>

**Comment by YASME-Tim** [comment]
This link is down, ssl mismatch - waiting for it to be up
