### ISSUE TITLE
Missing Scoreboards

### ISSUE THREAD

**Issue by tjgerot** [ctfs/write-ups-2016#1692]
Scoreboards are missing for the following 18 competitions (2016):
- [x] Codegate
- [x] Backdoor
- [x] Whitehat
- [x] Labyrenth
- [x] NuitDuHack
- [x] TU CTF
- [x] TJCTF
- [x] ABCTF
- [x] Securinets
- [x] Teaser Confidence
- [x] StHack
- [x] Security Fest
- [x] HITB CTF
- [x] HACKCON
- [x] ALICTF
- [x] UFO CTF
- [x] DEFCON Qualifier
- [x] Boston Key Party

An effort should be made to acquire these scoreboards from the web, or from competition hosts.

**Comment by abpolym** [comment]
@tjgerot You can use [getscores.py](https://github.com/ctfs/write-ups-tools/blob/master/getscores.py) to generate scoreboards from CTFTime scoreboards. E.g. for TU CTF you can download the scoreboard with `python getscores.py https://ctftime.org/event/312`. Make sure the scoreboard isn't missing on CTFTime, too, though.

**Comment by tjgerot** [comment]
It works! Thank you.
