### ISSUE TITLE
You have cthulusoft for hack.lu 2016 twice

### ISSUE THREAD

**Issue by Grazfather** [ctfs/write-ups-2016#2455]
https://github.com/ctfs/write-ups-2016/tree/master/hack.lu-ctf-2016/reversing/cthulhusoft-350
https://github.com/ctfs/write-ups-2016/tree/master/hack.lu-ctf-2016/reversing/cthulusoft-350

**Comment by tjgerot** [comment]
Thanks for letting us know!

**Comment by Grazfather** [comment]
Any time!
