### ISSUE TITLE
Sharif 2016 RE 100 Android

### ISSUE THREAD

**Issue by Grazfather** [ctfs/write-ups-2016#265]
http://grazfather.github.io/ctf/re/2016/02/14/Sharif-CTF-RE100-Android-App-Writeup.html

For page https://github.com/ctfs/write-ups-2016/tree/master/su-ctf-2016/reverse/android-app-100

**Comment by abpolym** [comment]
Thanks @Grazfather

**Comment by Grazfather** [comment]
Thank you!
