### ISSUE TITLE
New writeups for RC3 CTF 2016

### ISSUE THREAD

**Issue by 0xd13a** [ctfs/write-ups-2016#2841]
Hi, I posted a bunch of writeups for this CTF, feel free to link to them. Thanks!

https://0xd13a.github.io/RC3-CTF-2016-Writeups/

**Comment by tjgerot** [comment]
Added. We always appreciate your write-ups!

**Comment by 0xd13a** [comment]
Thanks Thomas. I noticed that you have a bot collecting these from ctftime.org. Does it mean that there is no need to notify you of new writeups if they were posted to CTFTime already?

**Comment by tjgerot** [comment]
Nope. The write-ups-bot collects writeups as they are posted to CTFtime so if you add them to a challenge, it will make its way into our repository.
