### ISSUE TITLE
Break In

### ISSUE THREAD

**Issue by YASME-Tim** [ctfs/write-ups-2016#31]

**Comment by ParthKolekar** [comment]
We would be sending them to you ASAP.

**Comment by YASME-Tim** [comment]
@ParthKolekar Thanks for collecting all challenges and sending them. BTW do you also happen to have official solutions (or flags/ways) for the challenges listed as missing [here](https://github.com/ctfs/write-ups-2015/tree/master/break-in-ctf-2015) from your last CTF?

**Comment by ParthKolekar** [comment]
I will contact the team from last year and try to get them up.

**Comment by YASME-Tim** [comment]
@ParthKolekar Any news?

**Comment by ParthKolekar** [comment]
I was unable to get the team from last year to contribute to writeups. 
The writeups for this year are delayed a bit due to impending mid-term examinations. 

Expect a pull request for this break-in-16 by 10th Feb.

**Comment by YASME-Tim** [comment]
@ParthKolekar Ok cool! Thanks for the quick response!

**Comment by YASME-Tim** [comment]
@ParthKolekar Pull Request incoming? :)

**Comment by ParthKolekar** [comment]
Partially Fixed via #249 

There are two questions still pending and one question requiring additional explanation. I'll complete those and send it up.

**Comment by YASME-Tim** [comment]
@ParthKolekar Thanks - I'll leave open the issue. I'll move the tasks though into their respective categories and rename them to fit the usual format

**Comment by YASME-Tim** [comment]
@ParthKolekar https://github.com/ctfs/write-ups-2016/tree/master/breakin-ctf-2016/steganography/make-pair-200 also needs the image file - and maybe can you add the source files for web challenges? Thanks for your help!

**Comment by ParthKolekar** [comment]
10-4!

Will do!

**Comment by ParthKolekar** [comment]
#261 

Should fix everything.

**Comment by YASME-Tim** [comment]
@ParthKolekar Yup, should be done now

**Comment by abpolym** [comment]
@ParthKolekar Just a question to the writeups: They've been written all by you? I've added you as the author for all of these writeups - if that is false, please tell me so (mention me with @abpolym)

**Comment by ParthKolekar** [comment]
I am the author for all the write-ups which are written. 

I am the author for problem "Knock Knock" only. 

Since I knew the answers, I wrote write-ups for them all.

**Comment by abpolym** [comment]
@ParthKolekar Ok thanks for the confirmation :)
