### ISSUE TITLE
ABCTF 2016 Caesar Salad (Cryptography) team OMECA

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2016#3280]
_From @write-ups-bot on February 8, 2017 17:43_

http://ift.tt/2ks38pS<br>
[click on title to read at ctftime.org]<br>

_Copied from original issue: ctfs/write-ups-2017#274_

**Comment by tjgerot** [comment]
Resolved in [this commit](https://github.com/ctfs/write-ups-2016/commit/ec35a2bdbcf18e33e4a4b7fa4a5be28f12fde953).
