### ISSUE TITLE
Missing ctf binary

### ISSUE THREAD

**Issue by Agahlot** [ctfs/write-ups-2016#3313]
There is a broken link for the Asis ctf quals challenge. [https://github.com/ctfs/write-ups-2016/tree/master/asisis-ctf-quals-2016/pwn/books-146/books](url)

**Comment by m1ghtym0** [comment]
Was my fuck up, I commited to the wrong dir, should be fixed now.
Here is the correct link: https://github.com/ctfs/write-ups-2016/raw/master/asis-ctf-quals-2016/pwn/book-146/books
