### ISSUE TITLE
Boston Key Party CTF + Future CTFs - Help needed.

### ISSUE THREAD

**Issue by abpolym** [ctfs/write-ups-2016#550]
Didn't collect the challenges for this CTF and don't have time for future CTFs to collect the stuff. Help by other contributors is wanted and needed if this repository is to stay up to date and be able to provide help to others.

**Comment by crowell** [comment]
all tasks are here http://captf.com/2016/bostonkeyparty/

**Comment by boogy** [comment]
What kind of help you'd like to have?

**Comment by abpolym** [comment]
@boogy Help with maintaining the repo: Collecting the tasks and pushing them to the repo as soon as the CTF ends - or searching for writeups for tasks with no links so far.

**Comment by dhanvi** [comment]
@crowell Thanks for the mention of files, I was thinking if the tasks at the ctftime.org https://ctftime.org/event/252/tasks/ are complete 

I will put the placeholders for the Boston Key part but I need some time :smile:

**Comment by dhanvi** [comment]
Since the files were there I can easily add them to the repo, so I am assigning it to myself

**Comment by dhanvi** [comment]
@boogy join here https://gitter.im/ctfs/write-ups and have a chat with us if you would like to contribute to the project :smile:

**Comment by dhanvi** [comment]
@abpolym I am closing this issue as of now as we will create a new issue for every CTF if we need help and none of us are free :+1:
