### ISSUE TITLE
Place holders for the Recent CTF's

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2016#685]
Looks like this time myself and @abpolym don't have time to put them, so some one else need to do it! 

- [x] https://ctftime.org/event/262 0ctf https://ctftime.org/event/262/tasks/

- [x] https://ctftime.org/event/299 codegate http://captf.com/2016/codegate/

- [x] https://ctftime.org/event/264 Bctf 

- [x] https://ctftime.org/event/297 Sunshine 

cc @mathiasbynens

**Comment by dhanvi** [comment]
https://github.com/ctfs/write-ups-2016/pull/692

**Comment by StephanDollberg** [comment]
Added the 0CTF structure

**Comment by abpolym** [comment]
Thanks @StephanDollberg

**Comment by dhanvi** [comment]
I will work on getting the codegate challange getting done http://captf.com/2016/codegate/

**Comment by dhanvi** [comment]
for now the issue is close but we have a bigger issue #241
