### ISSUE TITLE
Insomni'hack 2016 Solves stats

### ISSUE THREAD

**Issue by fbonzon** [ctfs/write-ups-2016#758]
You may add the number of Solves for each task from the official site: https://insomnihack.ch/?p=546

**Comment by dhanvi** [comment]
@fbonzon Thanks for the info 

currently we are having less number of contributors, so I think the focus should be on adding new writeup links and adding new ctfs 

but feel free to add the number of solves and create a PR and get it merged

**Comment by tjgerot** [comment]
I'll start on it.
