### ISSUE TITLE
Place Holders of Nuit du Hack CTF Quals 2016

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2016#861]
https://ctftime.org/event/284

**Comment by dhanvi** [comment]
@waywardsun would like to help us in adding the place holders of this ctf

**Comment by dhanvi** [comment]
@waywardsun did you get the challenges for the ctf ? any update 

if you got the challenges please email them to me I will add them here :+1:

**Comment by m1ghtym0** [comment]
@dhanvi everything was still up on https://www.nuitduhack.com/en/quals.html
added everything i could find

**Comment by dhanvi** [comment]
@m1ghtym0 I was just looking at the commit https://github.com/ctfs/write-ups-2016/commit/e0bcbac7247da4a62ed68cca58e4ddc064130565 

with you in our team we can make this repo more active :smile:

**Comment by m1ghtym0** [comment]
thanks:)
My plan was to close all the ctftime issues, so the repo stays synced with a all the external write-ups.
Following this we should focus on getting some repo-local write-ups in;-)
